### ISSUE TITLE
makeInvertable and invert()

### ISSUE THREAD

**Issue by curran** [ottypes/json1#11]
I'm wondering, is the type invertable?

I see the following in https://github.com/ottypes/json1/blob/19d855daace66334cbc7b40f8ba9d2827daf0dfc/lib/json1.js#L21

```
// - makeInvertable and invert()
```

What would be some first steps to implementing/verifying this? I suppose we could start with some failing tests.

Also the related to the ideas from [the spec](https://github.com/ottypes/json1/blob/923324d88cb8c9c117c6df457625f6f701a28904/spec.md#inverting-operations):

(quoting from there)

The JSON1 OT type is designed to be optionally invertible. There are no constraints on the content of `r:` components, so the contents of the removed elements can be placed there.

To implement this, we need a (unwritten) function which takes an operation and a document snapshot and augments all `r:X` components with the content to be removed.

Then an invert function can be written which:

- Swaps `i` and `r` components
- Swaps `p` and `d` components
- Move all edits to the item's source location
- Invert all embedded edits using the embedded type

In the current implementation the extra information in `r:X` components will be lost if the operation is transformed.

**Comment by josephg** [comment]
The plan is to have invertable operations be optional, but the work to support invertable operations hasn’t happened yet.

When you remove data, you can either specify r:true or r:(actual data to remove). Operations are *almost* symmetric - if they we’re we could just swap pick and drop, insert and remove to invert an operation. Unfortunately embedded edits break that rule. (To allow a held document component to be edited it has to be edited either before the pickup phase or after the drop phase). So there’s some work to do to write an invert function.

I can’t remember off the top of my head, but I think there’s one or two places where I was playing fast and loose with inverted data in transform, while I was fixing other issues. In the medium term I can imagine writing a makeInvertable(op, doc) -> op function which fills in all the removed data based on the document against which the operation can be applied. And because of the issues in transform, you might need to call that after transforming the document.

**Comment by curran** [comment]
Awesome. Thank you for clarifying.

The next increment of work I supposed would be to build out `makeInvertable(op, doc) -> op`.

**Comment by josephg** [comment]
I’d merge a PR with tests which added this functionality

**Comment by Jocs** [comment]
Is there any plan to implement this method now? Because i found it so useful for me, thanks for you great work.

**Comment by josephg** [comment]
Ummm yeah I'd love to do a cleanup pass at some point. Thanks for letting me know you find it useful!

It should be pretty easy to write, as far as these things go. Its just a matter of putting the time in to getting invert working and testing it.

**Comment by josephg** [comment]
I just finished a big pass converting all the code to typescript; so it might not be quite as scary to write invert now.

There's a few times where transform simply doesn't have the information needed to generate an invert operation. For example:

- A: Move X -> Y.X
- B: Delete Y

In this case the operation needs to also delete the contents of Y.X (which used to be in X), but we don't know what those objects are.

There's also times the current code throws away invertability information in compose, but I'm not sure if thats necessary or if I was just being lazy when I wrote the code.

My rough plan is to have a function with a signature like `type.makeInvertable(op, doc)` which would scan for `{r:xxx}` remove fields inside operation components and insert with the actual removed subdocument into the op. That should be pretty easy to write - y'all are welcome to give it a go if you want.

Once we have that it should be reasonably simple to write an invert function. It would just:

1. Swap all picks for drops, drops for picks, inserts for remove and remove for insert.
2. Embedded edits need to be recursively inverted using their type's invert function.
3. All embedded edits need to be reverse-transformed by the operation. Eg, `[[x, p:0], [y, d:0, es:...]]` needs to become `[[x, d:0, es:...], [y, p:0]]`. This is because edits are always applied in the context of the drop locations.

1 and 2 are easy. And 3 is ... well, its a much simpler problem than the logic that already exists in compose and transform. I mean, Compose() already has exactly the same logic for cases like compose(`[[x, p:0], [y, d:0]]`, `[y, r:true]`). In this case the r:true gets reverse-transformed by the move just like we need for edits.

Those are my notes. Feel free to give it a go if you're keen!

**Comment by curran** [comment]
Amazing!

**Comment by josephg** [comment]
I've just added [invertWithCtx](https://github.com/ottypes/docs/blob/master/README.md#optional-properties) as an optional (but recommended) method for ot types in general and I'm going to start by adding support for that in text-unicode and the fuzzer. Going forward, I think this is the cleanest API for actually making and using undo operations in the wild and I'd like to promote that to a required method in all types.

I'll also expose the helpers I described above for JSON1 and text-unicode, so you can make an invertable version of an operation for long term storage if you want. But its definitely going to be more complicated getting users to handle invertable and non-invertable operation variants, and then have to keep track of whether a given variable contains an operation thats invertable.

**Comment by josephg** [comment]
Small update: just [pushed support](https://github.com/ottypes/text-unicode/commit/f2e3e1c4d59cdf58e451d63520fb038e02f0eaf0) for this new API in [ot-text-unicode](https://github.com/ottypes/text-unicode) (which is a prereq to adding it here in json1).

I'd love some feedback on what to call the method that does this - we already have `invert(op)`. We need a different invert method which also takes in a document snapshot. Ummm?

Could go with:

- `invert2(op, doc)`
- `invertWithCtx(op, doc)`
- `invertWithDoc(op, doc)`

?? Thoughts?

**Comment by josephg** [comment]
Going with `invertWithDoc`. I also thought about just extending `invert` to have a 2-argument version. Changes to ot-text-unicode have been merged, and the new APIs are lightly documented in the readme. (There's actually more helper functions). Next step on this journey is getting equivalent methods for json1 code. (One method to add invertibility information into an operation - filling in the `{r:XX}` components with the actual data, and another method to invert).

**Comment by curran** [comment]
`invertWithDoc` is a great name.

**Comment by josephg** [comment]
I've done the first pass of this [here](https://github.com/ottypes/json1/commit/85c0da0db1e0639316b70b36ee2dd8f2402b80e2). As far as I know it works - but I've run into a problem that I'm not sure how to approach involving the current setNull behaviour.

Right now its possible to initialize a field and immediately edit it in the same operation. Eg: `[ {i: '', es: [ 'hi' ]} ]` (insert empty string '', then edit that string by inserting characters 'hi'). This seems weird - I mean, why not just insert the string 'hi' directly - ie `[{i: 'hi'}]` ? The reason the current behaviour exists is that it allows you to set a field based on a default value, and edit that field in a way that allows concurrent edits. The concurrent operations `[{i: 'hi'}]` vs `[{i: 'yo'}]` cause a conflict. But `[ {i: '', es: [ 'hi' ]} ]` vs `[ {i: '', es: [ 'yo' ]} ]` will merge correctly and result in a document of `'hiyo'`.

Today's horrifying realization is: What should the inverse of those setNull operations look like? `[ {r: '', es: [ {d:'hi'} ]} ]` is invalid because semantically the edit happens *after* the remove. By the time we try and remove the string 'hi' from the document, its already been deleted.

Another option (and maybe the only option) is to bake the edit inside the invert function - so the invert of the operation is `[{r: 'hi'}]`. But note that that isn't really the inverse. The problem here is that if user 1 types 'hi' and in their edit they initialize the document, and another user types something else, user 1 will delete both user's data when they hit undo. (Details below)

There might be ways around that for sharedb / etc to deal with. So sharedb could do something like this for its undo logic:

```javascript
initOp = [{i: ''}] // initialize the field
userOp = [{es: ['hi']}] // insert user's data

submitOp(compose(initOp, userOp)) // Send to the server the composed operation - [ {i: '', es: [ 'hi' ]} ]
// but have the undo operation be a little bit different
undo = invertWithDoc(userOp, apply(doc, initOp)) // The undo only removes the user's 'hi'. It does not delete the field.
```

Another trick which might help is that we're using a special `invertWithDoc` method to invert an operation. I could make that method understand setNull behaviour, such that `invertWithDoc([ {i: '', es: [ 'hi' ]} ], null)` returns `[{r: 'hi'}]` but `invertWithDoc([ {i: '', es: [ 'hi' ]} ], '')` returns `[{es: [{d: 'hi'}]}]`. This is probably more correct, but I can't think of ways it will actually help consumers of the library.

More nerdy detail:

Usually OT math works such that I can do this:

```
doc + op1 + op2 + transform(inv(op1), op2) = doc + op2
```

Ie, if two users make edits to the document, and on my computer my edit was applied first, I can use `transform(inv(op1), op2)` to transform my undo operation by the other user's operation. Then I can apply it to undo my edit, but preserve the other user's edit. This is really useful. But if `invert([{i: '', es: [ 'hi' ]}])` deletes the whole document, `transform(inv(op1), op2) will delete both user's edits. Not just user 1's edit.

**Comment by curran** [comment]
Intuitively a field should only be able to be initialized once, regardless of its value (empty string or otherwise). So, intuitively, I would think that `[ {i: '', es: [ 'hi' ]} ]` vs `[ {i: '', es: [ 'yo' ]} ]` perhaps _should_ result in a conflict, as they are both initializing the same field. I'm sure I'm missing something here about the design of this, but just thought I'd drop a note as I'm following this work from a distance.

Also, it's not clear that merging those two would result in `'hiyo'` independent of ordering - why not `'yohi'`? Is there some sorting rule internally that guarantees the same merge result regardless of order?

Another angle - I wonder what the probability of hitting this case is in practice. If it's quite low, probably a first version of invert could be released that doesn't handle this case, and it can just be clearly documented that this case is not handled.

Great work on this so far!

**Comment by josephg** [comment]
The conflict / setnull semantics were decided a few years ago. And “conflict” in this case is a bit vague / up to the user anyway. It falls back to the normal conflict semantics if the two users initialise the field to different values. I don’t think we lose anything with this behaviour, and this enables some handy use cases. (In particular, it makes adding new fields to documents much cleaner.)

And yes it could be ‘hiyo’ or ‘yohi’ depending on which operation ends up as the left / right op during transform.

I won’t release the invert implementation as is because it’s too broken. I’d rather a missing feature than a feature which crashes the server / loses user data.

**Comment by josephg** [comment]
Alright; I've done the fix to this problem that I suggested, baking inline edits when needed. And I fixed a bunch of other small bugs. I also made a tiny fuzzer for invert and sure enough, the first time I ran it it died after about 20 iterations.

Anyway, its now running over 10M iterations with no issues. I'm leaving it on overnight but I suspect at this point the invert logic might be correct.

There's still a few caveats:

- Compose doesn't preserve invert information in `{r:_}` components. This is fixable - it should more or less mirror the logic its already using for inserts. But it hasn't been fixed.
- For symmetry with text-unicode, I'd like to have a `stripInvertible` method which replaces all `{r:_}` components with 1 or something to minify an operation.
- There's some subtlety in using invert with setNull (as I described above)
- Right now `invertWIthDoc` is internally just a wrapper for `invert(makeInvertible(op, doc))`. This works great for subtypes which implement invert (including via makeInvertible). But if a subtype only implements `invertWithDoc`, the code can't invert the child operation at the moment.

But with all that said, tomorrow if there's no surprises I'll add some documentation then publish a new version with invert support. 🎉

**Comment by Jocs** [comment]
>But with all that said, tomorrow if there's no surprises I'll add some documentation then publish a new version with invert support. 🎉

Great work, Looking forward to your release, I will try it out as soon as possible.

**Comment by curran** [comment]
Hooray!

**Comment by josephg** [comment]
It ran correctly for 100M operations, so I think I can happily say invert is correct.

📦 ot-json1@1.0  O_o 💃
