### ISSUE TITLE
Generating Diffs

### ISSUE THREAD

**Issue by Immortalin** [ottypes/json1#13]
https://github.com/kbadk/json0-ot-diff

^Can this feature be added to the json1 codebase?

**Comment by josephg** [comment]
No; I'd prefer it stayed out of tree. The reason is there's usually multiple operations you could make to transform one document into another, and the semantics are all different. Consider [1,2] -> [2,1]. The operation could be:

- {delete item 0, insert 1 at position 1}
- {move item 0 to location 1}
- {move item 1 to location 0}
- Delete the whole document and replace it with [2,1]
- ... etc

Of course if people want to use libraries like that they're welcome to; but the recommended use should involve crafting operations based on the user's actions; not simply reverse engineered based on how the data appears to have changed.

**Comment by curran** [comment]
JSON1 diffing has landed in https://github.com/kbadk/json0-ot-diff
