### ISSUE TITLE
Moving array element into subkey of later element

### ISSUE THREAD

**Issue by gvatn** [ottypes/json1#16]
When moving an array element into a subkey of a later element,
I believe the path could use adjusting when the picked up element is
on a previous index.

Illustration:
https://codesandbox.io/s/happy-moon-3b295?file=/src/index.js

**Comment by josephg** [comment]
Yeah the api here is a bit confusing.

The way to think about it is move(path before op, path after op). So if you want to move an item later in an array, move([0], [1]) makes sense because after the move, you want the item will be at index 1. But in the second example, after the operation has been performed the moved item will be at path [“list”, 0, “sub”, 0]. So that’s what you need to pass to the move function.

I hear that it’s counterintuitive. I’m open to suggestions here but I can’t think of a better rule which is simpler to work with. If we made the second path not take into account the pick up, then the second example would be simpler but the first example would be need to say move(0, 2) instead. And that would be equally confusing. I figure at least this way there’s a consistent rule. (“Where does it end up in the result? That’s the second argument for moveOp.”)

**Comment by gvatn** [comment]
Thanks. It seems a perfectly reasonable api with a bit more clarity in my understanding.

I was implementing a backend for slate editor, which has different semantics for it's move operation. 
(Adaptation: https://github.com/gvatn/editor/blob/a0bfe6690386582c41cf64abfd9aa2a49c05ab99/packages/next/components/SlateAdapter.ts#L60-L73)

Their destination was based on the document before the pick-up, contributing to some confusion.

I think what matters is just knowing how it works.

**Comment by gvatn** [comment]
Thanks. It seems a perfectly reasonable api with a bit more clarity in my understanding.

I was implementing a backend for slate editor, which has different semantics for it's move operation.
(Adaptation: https://github.com/gvatn/editor/blob/eadfc439b0d049ea527e71ff805d2b416a1251fe/packages/next/components/SlateAdapter.ts#L59-L92)

Their destination was based on the document before the pick-up, contributing to some confusion.

I think what matters is just knowing how it works.

**Comment by josephg** [comment]
At some point it might make sense to add both variants in helper methods.

**Comment by josephg** [comment]
(Also very cool - thanks for sharing that you’re making a slate editor adaptor!)

**Comment by josephg** [comment]
If anyone else is running into this, you can make an adaptor function using the transformPosition helper:

```javascript
const {type, moveOp, removeOp} = require('ot-json1')

function moveOpPre(fromPath, toPathPre) {
  const toPathPost = type.transformPosition(toPathPre, removeOp(fromPath))
  return moveOp(fromPath, toPathPost)
}
```

Eg:

`moveOpPre(['list', 0], ['list', 1, 'sub', 0])` returns the equivalent of `moveOp(['list', 0], ['list', 0, 'sub', 0])` 

transformPosition will return null if you try to move an object into itself.
